{
 "title": "Particulate",
 "tags": [
  "air-quality",
  "particulate"
 ],
 "time": { "from": "2026-07-06T04:41:10.584Z", "to": "2026-07-06T12:00:10.478Z" },
 "panels": [
  { "title": "PM2.5", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current stable (15m median)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile_over_time(0.5, pm25[15m])",
     "legendFormat": "PM2.5 current stable"
    }
   ]
  },
  {
   "title": "1h average",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg_over_time(pm25[1h])", "legendFormat": "PM2.5 1h average" }
   ]
  },
  {
   "title": "24h average",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg_over_time(pm25[24h])", "legendFormat": "PM2.5 24h average" }
   ]
  },
  {
   "title": "Trend (30m average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    { "expr": "avg_over_time(pm25[30m])", "legendFormat": "PM2.5 30m average" }
   ]
  },
  { "title": "PM10", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Current stable (15m median)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile_over_time(0.5, pm10[15m])",
     "legendFormat": "PM10 current stable"
    }
   ]
  },
  {
   "title": "1h average",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg_over_time(pm10[1h])", "legendFormat": "PM10 1h average" }
   ]
  },
  {
   "title": "24h average",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg_over_time(pm10[24h])", "legendFormat": "PM10 24h average" }
   ]
  },
  {
   "title": "Trend (30m average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    { "expr": "avg_over_time(pm10[30m])", "legendFormat": "PM10 30m average" }
   ]
  }
 ]
}