apiVersion: v1
kind: Service
metadata:
  name: airdata-particulate
  namespace: monitoring
  labels:
    app: airdata-particulate
spec:
  type: ClusterIP
  selector:
    app: airdata-particulate
  ports:
    - name: metrics
      port: 8000
      targetPort: metrics
